config/routes.rb
Mymdb::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :genres

  resources :films
  resources :search, :only => :create

  root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/film.rb
class Film < ActiveRecord::Base
  
  before_validation :clean_url
  
  belongs_to :genre
  
  validates_presence_of :name, :url, :description
  validates_numericality_of :rating, :greater_than => -1, :less_than => 6 
  # attr_accessible :name, :url, :description, :rating
  
  private 
  def clean_url
    self.url.gsub!("http://",'') if self.url
  end
  
end


# == Schema Information
#
# Table name: films
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  url         :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  rating      :integer
#

app/models/genre.rb
class Genre < ActiveRecord::Base
  
  has_many :films, :dependent => :destroy
  
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  
  before_filter :authenticate_admin!, :except => [:index, :show]
  
  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(params[:film])
    if @film.save
      redirect_to @film, :notice => "Successfully created film."
    else
      render :action => 'new'
    end
  end

  def edit
    @film = Film.find(params[:id])
  end

  def update
    @film = Film.find(params[:id])
    if @film.update_attributes(params[:film])
      redirect_to @film, :notice  => "Successfully updated film."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to films_url, :notice => "Successfully destroyed film."
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(params[:genre])
    if @genre.save
      redirect_to @genre, :notice => "Successfully created genre."
    else
      render :action => 'new'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      redirect_to @genre, :notice  => "Successfully updated genre."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, :notice => "Successfully destroyed genre."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def create
    search = "%#{params[:search_for]}%"
    @films = Film.find(:all, :conditions => ['name LIKE ?', search])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def admin_or_user 
    return "admin" if admin_signed_in?
    return "user" if user_signed_in?
  end
  
  def sign_out_path
    return destroy_user_session_path if user_signed_in?
    return destroy_admin_session_path if admin_signed_in?
  end
  
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
  
  def genre_options
    options = Genre.all.collect do |genre|
      [genre.name, genre.id]
    end
  end
  
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/authentication/_sign_in.html.erb
<%= link_to "sign in as admin", new_admin_session_path %> | <%= link_to "sign in as user", new_user_session_path %>

app/views/authentication/_sign_out.html.erb
You are signed in as <%= admin_or_user%> <%= (current_user || current_admin).email %>
<%= link_to "sign_out", sign_out_path %>

app/views/films/_form.html.erb
<%= form_for @film do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
	<%= f.label :rating %><br />
	<%= f.select :rating, (0..5) %>
  </p>
  <p>
	<%= f.label :genre %><br />
	<%= f.select :genre_id, genre_options %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/films/edit.html.erb
<% title "Edit Film" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @film %> |
  <%= link_to "View All", films_path %>
</p>

app/views/films/index.html.erb
<% title "Films" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Description</th>
  </tr>
  <% for film in @films %>
    <tr>
      <td><%= film.name %></td>
      <td><%= film.url %></td>
      <td><%= film.description %></td>
	  <td><%= film.rating %></td>
	  <td><%= film.genre.name %></td>
      <td><%= link_to "Show", film %></td>
      <td><%= link_to "Edit", edit_film_path(film) %></td>
      <td><%= link_to "Destroy", film, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Film", new_film_path %></p>

app/views/films/new.html.erb
<% title "New Film" %>

<%= render 'form' %>

<p><%= link_to "Back to List", films_path %></p>

app/views/films/show.html.erb
<% title "Film" %>

<p>
  <strong>Name:</strong>
  <%= @film.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @film.url %>
</p>
<p>
  <strong>Description:</strong>
  <%= raw RedCloth.new(@film.description).to_html %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @film.rating %>
</p>
<p>
  <strong>Genre:</strong>
  <%= @film.genre.name %>
</p>

<p>
  <%= link_to "Edit", edit_film_path(@film) %> |
  <%= link_to "Destroy", @film, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", films_path %>
</p>

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/genres/edit.html.erb
<% title "Edit Genre" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @genre %> |
  <%= link_to "View All", genres_path %>
</p>

app/views/genres/index.html.erb
<% title "Genres" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for genre in @genres %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "Show", genre %></td>
      <td><%= link_to "Edit", edit_genre_path(genre) %></td>
      <td><%= link_to "Destroy", genre, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Genre", new_genre_path %></p>

app/views/genres/new.html.erb
<% title "New Genre" %>

<%= render 'form' %>

<p><%= link_to "Back to List", genres_path %></p>

app/views/genres/show.html.erb
<% title "Genre" %>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <%= link_to "Edit", edit_genre_path(@genre) %> |
  <%= link_to "Destroy", @genre, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", genres_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id ="authentication">
		<%= render :partial => 'authentication/sign_in' unless user_signed_in? || admin_signed_in? %>
		<%= render :partial => 'authentication/sign_out' if user_signed_in? || admin_signed_in? %>
	</div>
    <div id="container">
	  <h1>Sly Films</h1>
		<div>
			<div id = "navigation">
				<%= link_to 'Home', root_path %>
				<%= link_to 'Films', films_path %>
				<%= link_to 'Genres', genres_path %>
			</div>
      		<div id="search">
				<% form_tag search_index_path do %>
				<%= text_field_tag :search_for %>
				<%= submit_tag 'Go' %>
				<% end %>
	  		</div>
			<div style="clear:both;"></div>
		</div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/create.html.erb
<% @films.each do |film| %>
	<p><%= link_to film.name, film_path(film) %></p>
<% end %>